# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 02:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortly_app', '0002_auto_20180625_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortly',
            name='guest',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='shortly',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shortlies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shortlyinfo',
            name='guest',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='shortlyinfo',
            name='link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='shortly_app.Shortly'),
        ),
    ]
